version: '3.9'

services:
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT_LOCAL}:${POSTGRES_PORT_DOCKER}
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  web:
    build:
      context: web
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT_DOCKER}
    ports:
      - ${BACKEND_PORT_LOCAL}:${BACKEND_PORT_DOCKER}
    volumes:
      - ./web:/app/web
    depends_on:
      - db
