# Generated by Django 5.0 on 2023-12-11 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
        ('friend', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_friend_list', to='friend.friendlist'),
        ),
    ]
