# Generated by Django 5.0 on 2023-12-19 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
