# Generated by Django 5.0 on 2023-12-20 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0008_user_avatar'),
        ('game', '0004_gamestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_game_stats', to='game.gamestats'),
        ),
    ]
